services:
  faz-bot-collect:
    image: ghcr.io/fazuh/faz-bot-collect:latest
    container_name: faz-bot-collect
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql # Override .env
    env_file: .env
    expose:
      - 8000
    networks:
      - faz-bot-network
    volumes:
      - ./logs:/app/logs

  mysql:
    image: mariadb:11.4.2
    container_name: mysql
    restart: unless-stopped
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    env_file: .env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - faz-bot-network

volumes:
  mysql:
    name: mysql
    external: true

networks:
  faz-bot-network:
    name: faz-bot-network
    external: true
